### ISSUE TITLE
.Ark to json example?

### ISSUE THREAD

**Issue by vertyco** [miragedmuk/ArkSaveVisualiser#2]
Hi, i've been writing in python for about 10 months now and feel fairly comfortable with it, however C# is still super foreign to me. Would you be able to provide a script or quick rundown for how i can get the .Ark map file converted to json so i can use it with python?

Thanks for your time!

**Comment by miragedmuk** [comment]
Good morning @vertyco 

You can download the latest compiled build from the Survive The Ark forums and use either ArkExport.exe or ArkViewer.exe by passing in command line options.

ArkViewer.exe <option> <inputFile> <exportPath>

Available options:

- all (will output a file for each type)
- structures
- logs
- tribes
- players
- wild
- tamed

Example for exporting all data: 
- ArkViewer.exe all "C:\Ark\TheIsland.ark" "C:\Ark\Output\"

Example for exporting specific data:
- ArkViewer.exe tamed "C:\Ark\TheIsland.ark" "C:\Ark\Output\tamed.json"

**Comment by vertyco** [comment]
Thanks for that, youve done some great work! I hope to eventually understand the .ark files enough to parse them in python too!

**Comment by miragedmuk** [comment]
I only extended the work of others.  The file parsing is all done in the toolkit library I adapted and use in my own work which itself was adapted from a Java version if that's any better for you to learn from?

https://github.com/Qowyn/ark-savegame-toolkit

**Comment by vertyco** [comment]
I've seen his as well thank you, i have both saved, debating which one i should try to learn first lol. I can read the .ark file as bytes in python but parsing it as little-endian style is the next step, finding where that happens in ark-tools is my goal

**Comment by vertyco** [comment]
Are there any additional command line arguments? like how many threads to use or whether or not to produce the asvlog.log files?

**Comment by miragedmuk** [comment]
No options to limit the number of threads but you can change Nlog.config to amend some log file stuff.

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true" >

  <targets>
    <target xsi:type="File"
        name="logFile"
        fileName="asvlog.log"
        archiveFileName="asvlog.{#}.log"
        archiveEvery="Hour"
        archiveDateFormat="yyyyMMddHH"
        archiveNumbering="Date"
        maxArchiveFiles="3"
        layout="${longdate}|${level:uppercase=true}|${message}${exception:format=ToString,StackTrace}"
     />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="logFile" />
  </rules>
</nlog>

**Comment by vertyco** [comment]
Sweet that works, and thanks again the work youve done is awesome!

**Comment by vertyco** [comment]
Here's what ive been up to with it if you were curious
![Screenshot_20220505-020455_Discord](https://user-images.githubusercontent.com/58824393/166870389-636ff89f-3bcb-4ff2-955c-03ad50689a3f.jpg)

**Comment by vertyco** [comment]
![Screenshot_20220505-020736_Discord](https://user-images.githubusercontent.com/58824393/166870603-a47ed957-510e-44e6-9ad3-820edc9cb27f.jpg)

**Comment by miragedmuk** [comment]
I like the structure heat map. Nice way of showing population density without revealing too much detail.  I believe most people use my app for server administration from what I can tell - monitoring pillaring spam, finding missing dinos, op items etc.  

Personally I only made it to help identify exact locations and stats of wilds to tame and add to my own tribes dinos for breeding.  It expanded a little since then :)

**Comment by vertyco** [comment]
Hey i noticed that the export function doesnt include whether a tamed dino has mating enabled yet it shows if its enabled in the client, is there an argument to include this?

**Comment by miragedmuk** [comment]
I've stopped updating this branch and migrated everything to .net 6.0 in the new project ASV but will add whether they have breeding enabled in the next build of that branch - probably later in the week as I have a few things on at work this week.
